---

# General package installs
- name: Install general packages
  ansible.builtin.package:
    update_cache: true
    name: "{{ item }}"
    state: latest
  with_items:
    - bind9-dnsutils 
    - tcpdump 
    - nmap 
    - mysql-client
  become: true